### ISSUE TITLE
Latest codebase fails with JSON output format for logging

### ISSUE THREAD

**Issue by lyricnz** [Innablr/revolver#423]
The latest codebase fails when the log method is set to JSON:

```
Running revolver at timestamp [2024-08-20T03:30:18.731Z]
TypeError: Cannot read properties of undefined (reading 'logLevelId')
    at restructureJsonLog (file:///Users/robers19/src/github/CloudFinOps/cloudsnooze-source/lib/logger.js:66:76)
    at Object.transportJSON (file:///Users/robers19/src/github/CloudFinOps/cloudsnooze-source/lib/logger.js:104:13)
    at ErrorTrackingLogger.log (file:///Users/robers19/src/github/CloudFinOps/cloudsnooze-source/node_modules/tslog/dist/esm/BaseLogger.js:105:44)
    at ErrorTrackingLogger.info (file:///Users/robers19/src/github/CloudFinOps/cloudsnooze-source/node_modules/tslog/dist/esm/index.js:26:22)
    at handler (file:///Users/robers19/src/github/CloudFinOps/cloudsnooze-source/revolver.js:31:12)
    at file:///Users/robers19/src/github/CloudFinOps/cloudsnooze-source/invoke.js:29:11
    at ModuleJob.run (node:internal/modules/esm/module_job:262:25)
    at async onImport.tracePromise.__proto__ (node:internal/modules/esm/loader:482:26)
    at async asyncRunEntryPointWithESMLoader (node:internal/modules/run_main:117:5)
```

**Comment by lyricnz** [comment]
It looks like this is due to changing (global) isNaN() to Number.isNaN() - they have different semantics around type-conversion.

**global:**
```javascript
/**
 * Returns a Boolean value that indicates whether a value is the reserved value NaN (not a number).
 * @param number A numeric value.
 */
declare function isNaN(number: number): boolean;
```

**Number.isNan()**
```javascript
    /**
     * Returns a Boolean value that indicates whether a value is the reserved value NaN (not a
     * number). Unlike the global isNaN(), Number.isNaN() doesn't forcefully convert the parameter
     * to a number. Only values of the type number, that are also NaN, result in true.
     * @param number A numeric value.
     */
    isNaN(number: unknown): boolean;
```

For the following piece of code, which attempts to remove "non numbers", this results in all items being removed (from a set of `["0","1","_meta"]` - rather than just `_meta`

```javascript
  const positionalEntries: string[] = Object.keys(log).filter((k: any) => !Number.isNaN(k));
```

**Comment by lyricnz** [comment]
PS: we should have a test that uses JSON output formatting, just to catch this kind of issue

**Comment by lyricnz** [comment]
Will PR a quick revert for this change (in two places), but a better fix would be to be more explicit about type-conversion.
